env:
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
overrides:
  - files: "*.test.js"
    globals:
      test: "readonly"
      expect: "readonly"